MVCImageGallery/Controllers/ImageGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCImageGallery.Controllers
{
    public class ImageGalleryController : Controller
    {
        //
        // GET: /ImageGallery/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            List<ImageGallery> all = new List<ImageGallery>();
            
            // Here MyDatabaseEntities is our datacontext
            using (MyDatabaseEntities dc = new MyDatabaseEntities())
            {
                all = dc.ImageGalleries.ToList();
            }
            return View(all);
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(ImageGallery IG)
        {
            // Apply Validation Here

            
            if (IG.File.ContentLength > (2*1024*1024))
            {
                ModelState.AddModelError("CustomError", "File size must be less than 2 MB");
                return View();
            }
            if (!(IG.File.ContentType == "image/jpeg" || IG.File.ContentType == "image/gif"))
            {
                ModelState.AddModelError("CustomError", "File type allowed : jpeg and gif");
                return View();
            }

            IG.FileName = IG.File.FileName;
            IG.ImageSize = IG.File.ContentLength;

            byte[] data = new byte[IG.File.ContentLength];
            IG.File.InputStream.Read(data, 0, IG.File.ContentLength);

            IG.ImageData = data;
            using (MyDatabaseEntities dc = new MyDatabaseEntities())
            {
                dc.ImageGalleries.Add(IG);
                dc.SaveChanges();
            }
            return RedirectToAction("Gallery");
        }
    }
}

MVCImageGallery/Views/ImageGallery/Gallery.cshtml
@model List<MVCImageGallery.ImageGallery>
@{
    ViewBag.Title = "Gallery";
}
<h2>Gallery</h2>
<p>
    @Html.ActionLink("Upload New", "Upload")
</p>
@* Here I will show Uploaded Images *@
<table>    
    @{
        int j = 0;
        for (int i = 0; i < Model.Count(); i+=4)
        {
            j = i;
            <tr>
                @* I have done this for show 4 images in  a Row *@
                @while (j < i+4 && j < Model.Count())
	            {
                    <td>
                        <img src="data:image/png;base64,@Convert.ToBase64String(Model[j].ImageData,0,Model[j].ImageData.Length)" width="100" />
                    </td>
                    j++;
	            }
            </tr>
        }
    }
</table>

MVCImageGallery/Views/ImageGallery/Upload.cshtml
@model MVCImageGallery.ImageGallery
@{
    ViewBag.Title = "Upload";
}
<h2>Upload</h2>
@using (Html.BeginForm("Upload","ImageGallery", FormMethod.Post,new{enctype="multipart/form-data"}))
{
    @Html.ValidationSummary(true)
    <table>
        <tr>
            <td>Select File : </td>
            <td>
                @Html.TextBoxFor(Model=> Model.File, new{type="file"})
                @Html.ValidationMessage("CustomError")
            </td>
            <td>
                <input type="submit" value="Upload" />
            </td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}